version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Graphql_DEV
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - graphql-dev

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - graphql-dev
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
    pgadmin:
networks:
  graphql-dev:
    driver: bridge  